apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yaml
  - hpa.yaml
  - secret.yaml

patches:
  - path: ./patches/rollouts.yaml
  - path: ./patches/ingress.yaml

transformers:
  - ./kustomizeconfig/namesuffixtransformer.yaml
  - ./kustomizeconfig/dd-transformer.yaml

images:
  - name: IMAGE_NAME/PATH:TAG
    newName: k8s-demo-backend
    newTag: latest

labels:
  - includeSelectors: true
    pairs:
      app: k8s-demo-backend
